import type {
  AchievementDef,
  BossDef,
  BuildingDef,
  CollectionDef,
  DailyLoginDef,
  EnemyDef,
  EventDef,
  ItemDef,
  LootTableDef,
  QuestDef,
  ShopProductDef,
  TerritoryDef,
  WarriorDef,
} from '../../../shared/types';
import { generatedCreatures } from './creatures.generated';
import { legacyEnemyDrops } from '../game/creatureStats';

export const quests: QuestDef[] = [
  {
    id: 'hunt_boar',
    name: 'Hunt the Boar',
    description: 'Track a wild boar at the edge of the village.',
    category: 'hunting',
    chapter: 1,
    energyCost: 5,
    requiredLevel: 1,
    enemyId: 'wild_boar',
    rewards: { xp: 20, silver: 30, food: 8 },
    lootTableId: 'common_hunt',
  },
  {
    id: 'gather_wood',
    name: 'Fell the Pines',
    description: 'Gather timber for the hall.',
    category: 'gathering',
    chapter: 1,
    energyCost: 4,
    requiredLevel: 1,
    rewards: { xp: 15, silver: 10, wood: 20 },
  },
  {
    id: 'explore_shore',
    name: 'Walk the Shore',
    description: 'Scout the coastline for rival sails.',
    category: 'exploration',
    chapter: 1,
    energyCost: 6,
    requiredLevel: 2,
    rewards: { xp: 25, silver: 40 },
    lootTableId: 'common_hunt',
  },
  {
    id: 'raid_coastal_village',
    name: 'Raid the Coastal Village',
    description: 'Strike a poorly guarded coastal hamlet.',
    category: 'raiding',
    chapter: 1,
    energyCost: 8,
    requiredLevel: 3,
    enemyId: 'coastal_militia',
    rewards: { xp: 50, silver: 125, wood: 10 },
    lootTableId: 'coastal_raid',
  },
  {
    id: 'trade_amber',
    name: 'Amber for Iron',
    description: 'Bargain with a traveling merchant.',
    category: 'trading',
    chapter: 2,
    energyCost: 6,
    requiredLevel: 4,
    rewards: { xp: 35, silver: 80, iron: 12 },
  },
  {
    id: 'blood_on_the_coast',
    name: 'Blood on the Coast',
    description: 'Drive raiders from the strand.',
    category: 'warfare',
    chapter: 2,
    energyCost: 10,
    requiredLevel: 5,
    enemyId: 'rival_raider',
    rewards: { xp: 70, silver: 160 },
    lootTableId: 'warfare_loot',
  },
  {
    id: 'omen_ravens',
    name: "Odin's Ravens",
    description: 'Read the omens before the next voyage.',
    category: 'mythology',
    chapter: 2,
    energyCost: 7,
    requiredLevel: 5,
    rewards: { xp: 45, silver: 60 },
    lootTableId: 'relic_fragments',
  },
  {
    id: 'enemy_jarl_scout',
    name: 'The Enemy Jarl',
    description: 'Scout the rival jarl’s hall.',
    category: 'warfare',
    chapter: 3,
    energyCost: 12,
    requiredLevel: 7,
    enemyId: 'jarl_guard',
    rewards: { xp: 90, silver: 200, iron: 15 },
    lootTableId: 'warfare_loot',
  },
  {
    id: 'across_the_sea',
    name: 'Across the Sea',
    description: 'Launch longships toward a foreign coast.',
    category: 'exploration',
    chapter: 4,
    energyCost: 14,
    requiredLevel: 9,
    rewards: { xp: 110, silver: 220, wood: 25 },
    lootTableId: 'coastal_raid',
  },
  {
    id: 'northern_kingdom',
    name: 'The Northern Kingdom',
    description: 'March into frozen territory.',
    category: 'warfare',
    chapter: 5,
    energyCost: 16,
    requiredLevel: 12,
    enemyId: 'frost_champion',
    rewards: { xp: 150, silver: 300, iron: 20 },
    lootTableId: 'northern_loot',
  },
  {
    id: 'season1_ragnarok_scout',
    name: 'Ragnarok Scouts',
    description: 'Season 1 live-ops quest. Added via catalog, not an app release.',
    category: 'mythology',
    chapter: 5,
    energyCost: 10,
    requiredLevel: 8,
    rewards: { xp: 80, silver: 100, iron: 8 },
    lootTableId: 'relic_fragments',
  },
];

const legacyEnemies: EnemyDef[] = [
  {
    id: 'wild_boar',
    name: 'Wild Boar',
    type: 'animal',
    level: 1,
    attack: 12,
    defense: 6,
    health: 40,
    speed: 8,
    lootTableId: 'common_hunt',
    staminaCost: 1,
    drops: legacyEnemyDrops(1),
  },
  {
    id: 'coastal_militia',
    name: 'Coastal Militia',
    type: 'monster',
    level: 3,
    attack: 22,
    defense: 14,
    health: 70,
    speed: 12,
    lootTableId: 'coastal_raid',
    staminaCost: 2,
    drops: legacyEnemyDrops(3),
  },
  {
    id: 'rival_raider',
    name: 'Rival Raider',
    type: 'monster',
    level: 5,
    attack: 32,
    defense: 18,
    health: 90,
    speed: 14,
    lootTableId: 'warfare_loot',
    staminaCost: 2,
    drops: legacyEnemyDrops(5),
  },
  {
    id: 'jarl_guard',
    name: 'Jarl Guard',
    type: 'monster',
    level: 7,
    attack: 44,
    defense: 28,
    health: 120,
    speed: 16,
    lootTableId: 'warfare_loot',
    staminaCost: 3,
    drops: legacyEnemyDrops(7),
  },
  {
    id: 'frost_champion',
    name: 'Frost Champion',
    type: 'monster',
    level: 12,
    attack: 60,
    defense: 40,
    health: 180,
    speed: 20,
    lootTableId: 'northern_loot',
    staminaCost: 3,
    drops: legacyEnemyDrops(12),
  },
  {
    id: 'draugr',
    name: 'Draugr',
    type: 'monster',
    level: 10,
    attack: 55,
    defense: 35,
    health: 160,
    speed: 18,
    lootTableId: 'relic_fragments',
    staminaCost: 3,
    drops: legacyEnemyDrops(10),
  },
];

export const enemies: EnemyDef[] = [...legacyEnemies, ...generatedCreatures];

export const items: ItemDef[] = [
  {
    id: 'iron_axe',
    name: 'Iron Axe',
    slot: 'weapon',
    rarity: 'common',
    weaponType: 'axe',
    attack: 18,
    defense: 0,
    health: 0,
    speed: 0,
    description: 'A sturdy felling axe, equally at home in timber and in a shield wall.',
  },
  {
    id: 'oak_spear',
    name: 'Oak Spear',
    slot: 'weapon',
    rarity: 'uncommon',
    weaponType: 'spear',
    attack: 22,
    defense: 2,
    health: 0,
    speed: 0,
    description: 'A long oak shaft with a leaf-shaped head, built to keep foes at reach.',
  },
  {
    id: 'seax_blade',
    name: 'Seax',
    slot: 'weapon',
    rarity: 'common',
    weaponType: 'seax',
    attack: 14,
    defense: 0,
    health: 0,
    speed: 0,
    description: 'A single-edged fighting knife carried by every free Viking.',
  },
  {
    id: 'dane_axe',
    name: 'Dane Axe',
    slot: 'weapon',
    rarity: 'rare',
    weaponType: 'daneAxe',
    attack: 36,
    defense: 0,
    health: 0,
    speed: 0,
    description: 'A two-handed war axe whose wide blade can split helm and shield alike.',
  },
  {
    id: 'yew_bow',
    name: 'Yew Bow',
    slot: 'weapon',
    rarity: 'uncommon',
    weaponType: 'bow',
    attack: 24,
    defense: 0,
    health: 0,
    speed: 0,
    description: 'A self bow of seasoned yew, deadly from the prow of a longship.',
  },
  {
    id: 'iron_helm',
    name: 'Iron Helm',
    slot: 'helmet',
    rarity: 'common',
    attack: 0,
    defense: 8,
    health: 10,
    speed: 0,
    description: 'A simple iron cap with a nasal guard, enough to turn a glancing blow.',
  },
  {
    id: 'mail_shirt',
    name: 'Mail Shirt',
    slot: 'armor',
    rarity: 'uncommon',
    attack: 0,
    defense: 16,
    health: 25,
    speed: 0,
    description: 'Rings of iron linked by a smith’s patience, worn over a padded tunic.',
  },
  {
    id: 'round_shield',
    name: 'Round Shield',
    slot: 'shield',
    rarity: 'common',
    attack: 0,
    defense: 12,
    health: 8,
    speed: 0,
    description: 'Limewood boards bound in iron, painted with the mark of a clan.',
  },
  {
    id: 'raider_boots',
    name: 'Raider Boots',
    slot: 'boots',
    rarity: 'common',
    attack: 2,
    defense: 4,
    health: 5,
    speed: 0,
    description: 'Hard-soled leather boots for wet decks, frozen trails, and sudden charges.',
  },
  {
    id: 'wolf_ring',
    name: 'Wolf Ring',
    slot: 'ring',
    rarity: 'rare',
    attack: 8,
    defense: 4,
    health: 0,
    speed: 8,
    description: 'A silver band carved as a circling wolf, said to quicken the blood.',
  },
  {
    id: 'mjolnir_shard',
    name: "Thor's Hammer fragment",
    slot: 'amulet',
    rarity: 'epic',
    attack: 12,
    defense: 6,
    health: 10,
    speed: 0,
    description: 'A splinter of thunder-iron. It answers only to the Viking who found it.',
    bound: true,
  },
  {
    id: 'odin_raven',
    name: "Odin's Raven",
    slot: 'amulet',
    rarity: 'epic',
    attack: 6,
    defense: 10,
    health: 15,
    speed: 0,
    description: 'A raven charm of the Allfather. Bound to its bearer until death.',
    bound: true,
  },
  {
    id: 'ancient_rune',
    name: 'Ancient Rune',
    slot: 'ring',
    rarity: 'rare',
    attack: 5,
    defense: 5,
    health: 5,
    speed: 5,
    description: 'A carved stone ring whose meaning is lost, yet its power still binds.',
    bound: true,
  },
  {
    id: 'viking_crown',
    name: 'Viking Crown',
    slot: 'helmet',
    rarity: 'legendary',
    attack: 4,
    defense: 20,
    health: 30,
    speed: 0,
    description: 'A jarl’s iron circlet, worn by those who command the raid.',
  },
  {
    id: 'dragon_shield',
    name: 'Dragon Shield',
    slot: 'shield',
    rarity: 'legendary',
    attack: 0,
    defense: 28,
    health: 20,
    speed: 0,
    description: 'A hide-bound shield scaled like a wyrm, almost too heavy to lift.',
  },
  {
    id: 'season1_cloak_pin',
    name: 'Season 1 Cloak Pin',
    slot: 'amulet',
    rarity: 'rare',
    attack: 4,
    defense: 4,
    health: 8,
    speed: 0,
    description: 'A seasonal cloak pin awarded to those who sailed the first campaign.',
    bound: true,
  },
  {
    id: 'amber_necklace',
    name: 'Amber Necklace',
    slot: 'necklace',
    rarity: 'uncommon',
    attack: 2,
    defense: 2,
    health: 4,
    speed: 10,
    description: 'Baltic amber strung on leather, catching firelight like captured sun.',
  },
  {
    id: 'iron_bracelet',
    name: 'Iron Bracelet',
    slot: 'bracelet',
    rarity: 'common',
    attack: 1,
    defense: 2,
    health: 0,
    speed: 8,
    description: 'A twisted iron arm-ring, the first gift of a young warrior.',
  },
  {
    id: 'silver_bracelet',
    name: 'Silver Bracelet',
    slot: 'bracelet',
    rarity: 'uncommon',
    attack: 2,
    defense: 2,
    health: 2,
    speed: 10,
    description: 'A hammered silver ring that marks a successful raid.',
  },
  {
    id: 'raven_earrings',
    name: 'Raven Earrings',
    slot: 'earrings',
    rarity: 'rare',
    attack: 3,
    defense: 1,
    health: 0,
    speed: 12,
    description: 'Paired raven heads in bronze, worn to honor thought and memory.',
  },
  {
    id: 'leather_headband',
    name: 'Leather Headband',
    slot: 'headband',
    rarity: 'common',
    attack: 0,
    defense: 2,
    health: 4,
    speed: 6,
    description: 'A simple leather band that keeps sweat and hair from the eyes.',
  },
  {
    id: 'storm_headband',
    name: 'Storm Headband',
    slot: 'headband',
    rarity: 'rare',
    attack: 2,
    defense: 1,
    health: 0,
    speed: 14,
    description: 'A braided band darkened by sea-spray, favored by swift raiders.',
  },
];

export const lootTables: LootTableDef[] = [
  {
    id: 'common_hunt',
    dropChance: 0.25,
    entries: [
      { itemId: 'seax_blade', weight: 50 },
      { itemId: 'raider_boots', weight: 25 },
      { itemId: 'iron_axe', weight: 10 },
      { itemId: 'leather_headband', weight: 15 },
    ],
  },
  {
    id: 'coastal_raid',
    dropChance: 0.35,
    entries: [
      { itemId: 'iron_axe', weight: 40 },
      { itemId: 'round_shield', weight: 30 },
      { itemId: 'oak_spear', weight: 15 },
      { itemId: 'iron_bracelet', weight: 15 },
    ],
  },
  {
    id: 'warfare_loot',
    dropChance: 0.4,
    entries: [
      { itemId: 'mail_shirt', weight: 30 },
      { itemId: 'iron_helm', weight: 25 },
      { itemId: 'dane_axe', weight: 15 },
      { itemId: 'wolf_ring', weight: 10 },
      { itemId: 'amber_necklace', weight: 12 },
      { itemId: 'raven_earrings', weight: 8 },
    ],
  },
  {
    id: 'northern_loot',
    dropChance: 0.45,
    entries: [
      { itemId: 'yew_bow', weight: 25 },
      { itemId: 'dane_axe', weight: 25 },
      { itemId: 'viking_crown', weight: 5 },
      { itemId: 'dragon_shield', weight: 5 },
      { itemId: 'mail_shirt', weight: 20 },
      { itemId: 'storm_headband', weight: 10 },
      { itemId: 'silver_bracelet', weight: 10 },
    ],
  },
  {
    id: 'relic_fragments',
    dropChance: 0.5,
    entries: [
      { itemId: 'mjolnir_shard', weight: 20 },
      { itemId: 'odin_raven', weight: 20 },
      { itemId: 'ancient_rune', weight: 20 },
      { itemId: 'season1_cloak_pin', weight: 20 },
      { itemId: 'raven_earrings', weight: 20 },
    ],
  },
];

export const buildings: BuildingDef[] = [
  { id: 'greatHall', name: 'Great Hall', description: 'Controls overall progression.', maxLevel: 10, perLevelRate: 1 },
  { id: 'farm', name: 'Farm', description: 'Produces Food.', maxLevel: 10, produces: { food: 12 }, perLevelRate: 1 },
  { id: 'lumberCamp', name: 'Lumber Camp', description: 'Produces Wood.', maxLevel: 10, produces: { wood: 12 }, perLevelRate: 1 },
  { id: 'ironMine', name: 'Iron Mine', description: 'Produces Iron.', maxLevel: 10, produces: { iron: 8 }, perLevelRate: 1 },
  { id: 'blacksmith', name: 'Blacksmith', description: 'Crafts equipment.', maxLevel: 10, perLevelRate: 1 },
  { id: 'barracks', name: 'Barracks', description: 'Trains warriors.', maxLevel: 10, perLevelRate: 1 },
  { id: 'shipyard', name: 'Shipyard', description: 'Builds longships.', maxLevel: 10, perLevelRate: 1 },
  { id: 'tradingPost', name: 'Trading Post', description: 'Generates Silver.', maxLevel: 10, produces: { silver: 15 }, perLevelRate: 1 },
  { id: 'temple', name: 'Temple', description: 'Provides Norse blessings.', maxLevel: 10, perLevelRate: 1 },
];

export const warriors: WarriorDef[] = [
  {
    id: 'berserker',
    name: 'Berserker',
    class: 'berserker',
    rarity: 'rare',
    baseAttack: 80,
    baseDefense: 20,
    recruitCost: { silver: 200, food: 40 },
  },
  {
    id: 'shieldmaiden',
    name: 'Shieldmaiden',
    class: 'shieldmaiden',
    rarity: 'rare',
    baseAttack: 40,
    baseDefense: 70,
    recruitCost: { silver: 200, food: 40 },
  },
  {
    id: 'archer',
    name: 'Archer',
    class: 'archer',
    rarity: 'uncommon',
    baseAttack: 60,
    baseDefense: 25,
    recruitCost: { silver: 140, food: 25 },
  },
  {
    id: 'raider',
    name: 'Raider',
    class: 'raider',
    rarity: 'common',
    baseAttack: 50,
    baseDefense: 20,
    recruitCost: { silver: 100, food: 20 },
  },
];

export const territories: TerritoryDef[] = [
  { id: 'village', name: 'Your Village', requiredLevel: 1, requiredChapter: 1, energyCost: 0 },
  { id: 'coastalLands', name: 'Coastal Lands', requiredLevel: 3, requiredChapter: 1, energyCost: 8 },
  { id: 'northernForest', name: 'Northern Forest', requiredLevel: 6, requiredChapter: 2, energyCost: 10 },
  { id: 'frozenMountains', name: 'Frozen Mountains', requiredLevel: 9, requiredChapter: 3, energyCost: 12 },
  { id: 'enemyKingdom', name: 'Enemy Kingdom', requiredLevel: 12, requiredChapter: 4, energyCost: 14 },
  { id: 'legendaryLands', name: 'Legendary Lands', requiredLevel: 15, requiredChapter: 5, energyCost: 16 },
];

export const bosses: BossDef[] = [
  {
    id: 'enemy_jarl',
    name: 'Enemy Jarl',
    health: 400,
    attack: 70,
    defense: 40,
    speed: 16,
    staminaCost: 4,
    clanRaid: false,
    lootTableId: 'warfare_loot',
  },
  {
    id: 'frost_giant',
    name: 'Frost Giant',
    health: 10000,
    attack: 120,
    defense: 80,
    speed: 14,
    staminaCost: 5,
    clanRaid: true,
    lootTableId: 'northern_loot',
  },
  {
    id: 'sea_serpent',
    name: 'Sea Serpent',
    health: 8000,
    attack: 110,
    defense: 70,
    speed: 18,
    staminaCost: 5,
    clanRaid: true,
    lootTableId: 'coastal_raid',
  },
];

export const collections: CollectionDef[] = [
  {
    id: 'viking_relics',
    name: 'Viking Relics',
    itemIds: ['mjolnir_shard', 'odin_raven', 'ancient_rune', 'viking_crown', 'dragon_shield'],
    bonus: { attackPercent: 10 },
  },
  {
    id: 'season1_trophies',
    name: 'Season 1 Trophies',
    itemIds: ['season1_cloak_pin', 'wolf_ring'],
    bonus: { defensePercent: 5 },
  },
];

const now = Date.now();

export const events: EventDef[] = [
  {
    id: 'ragnarok',
    name: 'Ragnarok',
    description: '30-day event. Fight monsters, earn event currency and exclusive rewards.',
    startsAt: now - 24 * 60 * 60 * 1000,
    endsAt: now + 30 * 24 * 60 * 60 * 1000,
    currencyName: 'Doom Marks',
    rewards: ['Exclusive equipment', 'Avatar', 'Village decoration'],
  },
];

export const achievements: AchievementDef[] = [
  { id: 'first_blood', name: 'First Blood', description: 'Complete your first quest.' },
  { id: 'jarl', name: 'Jarl', description: 'Reach level 10.' },
  { id: 'warlord', name: 'Warlord', description: 'Win a PvP raid.' },
  { id: 'builder', name: 'Builder', description: 'Upgrade any building to level 3.' },
];

export const shopProducts: ShopProductDef[] = [
  {
    id: 'runes_small',
    name: 'Pouch of Runes',
    description: '80 Runes',
    productType: 'runes',
    runesGranted: 80,
    powerAffecting: false,
    storeSku: 'com.atomicdevs.vikingswar.runes_small',
  },
  {
    id: 'runes_large',
    name: 'Coffer of Runes',
    description: '500 Runes',
    productType: 'runes',
    runesGranted: 500,
    powerAffecting: false,
    storeSku: 'com.atomicdevs.vikingswar.runes_large',
  },
  {
    id: 'speedup_building',
    name: 'Builder’s Horn',
    description: 'Finish the current building upgrade.',
    productType: 'speedup',
    runeCost: 15,
    powerAffecting: false,
  },
  {
    id: 'avatar_wolfcloak',
    name: 'Wolfcloak',
    description: 'Cosmetic Viking outfit.',
    productType: 'cosmetic',
    runeCost: 40,
    cosmeticId: 'wolfcloak',
    powerAffecting: false,
  },
  {
    id: 'decor_longship',
    name: 'Harbor Longship',
    description: 'Village decoration.',
    productType: 'decoration',
    runeCost: 35,
    cosmeticId: 'harbor_longship',
    powerAffecting: false,
  },
  {
    id: 'battle_pass_s1',
    name: 'Season 1 Battle Pass',
    description: 'Premium track for Season 1.',
    productType: 'battlePass',
    runeCost: 120,
    powerAffecting: false,
  },
  {
    id: 'event_pass_ragnarok',
    name: 'Ragnarok Event Pass',
    description: 'Extra event rewards.',
    productType: 'eventPass',
    runeCost: 90,
    powerAffecting: false,
  },
];

export const dailyLogin: DailyLoginDef[] = [
  { day: 1, silver: 50 },
  { day: 2, silver: 75, food: 20 },
  { day: 3, silver: 100 },
  { day: 4, silver: 125, food: 30 },
  { day: 5, silver: 150 },
  { day: 6, silver: 200, food: 40 },
  { day: 7, silver: 250, runes: 5 },
];
