#!/usr/bin/env node
/**
 * Parses Vikings_War_500_Animals_and_Monsters.md into creatures.generated.ts
 * Usage: npx tsx scripts/parse-creatures.ts [path-to-md]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { computeCreatureStats } from '../functions/src/game/creatureStats';
import type { CreatureType, EnemyDef } from '../shared/types';
import { parseMaterials, parseRange, snakeCase } from './parse-creatures-lib';

const ROOT = resolve(__dirname, '..');
const DEFAULT_MD = resolve(
  process.env.HOME ?? '',
  'Downloads/Vikings_War_500_Animals_and_Monsters.md',
);
const MD_PATH = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_MD;
const OUT_PATH = resolve(ROOT, 'functions/src/seed/creatures.generated.ts');

interface ParsedRow {
  index: number;
  type: CreatureType;
  name: string;
  level: number;
  xp: string;
  silver: string;
  gold: string;
  materials: string;
}

function parseMarkdown(content: string): ParsedRow[] {
  const rows: ParsedRow[] = [];
  const lines = content.split('\n');
  for (const line of lines) {
    if (!line.startsWith('|')) {
      continue;
    }
    const cells = line
      .split('|')
      .map((cell) => cell.trim())
      .filter((cell, index, all) => !(index === 0 && cell === '') && !(index === all.length - 1 && cell === ''));
    if (cells.length < 8 || cells[0] === '#' || cells[0] === '---' || cells[0] === '#') {
      continue;
    }
    if (Number.isNaN(Number(cells[0]))) {
      continue;
    }
    const type = cells[1].toLowerCase() as CreatureType;
    if (type !== 'animal' && type !== 'monster') {
      continue;
    }
    rows.push({
      index: Number(cells[0]),
      type,
      name: cells[2],
      level: Number(cells[3]),
      xp: cells[4],
      silver: cells[5],
      gold: cells[6],
      materials: cells[7],
    });
  }
  return rows;
}

function buildEnemy(row: ParsedRow): EnemyDef {
  const id = `creature_${String(row.index).padStart(3, '0')}_${snakeCase(row.name)}`;
  const stats = computeCreatureStats(row.level, row.type, row.name);
  return {
    id,
    name: row.name,
    type: row.type,
    level: row.level,
    attack: stats.attack,
    defense: stats.defense,
    health: stats.health,
    speed: stats.speed,
    staminaCost: stats.staminaCost,
    lootTableId: 'common_hunt',
    portraitUrl: `creatures/${id}.webp`,
    drops: {
      experience: parseRange(row.xp),
      silver: parseRange(row.silver),
      gold: parseRange(row.gold),
      materials: { pool: parseMaterials(row.materials) },
    },
  };
}

function serializeEnemy(enemy: EnemyDef): string {
  return `  ${JSON.stringify(enemy, null, 2).split('\n').join('\n  ')},`;
}

function main(): void {
  const content = readFileSync(MD_PATH, 'utf8');
  const rows = parseMarkdown(content);
  if (rows.length === 0) {
    throw new Error(`No creature rows found in ${MD_PATH}`);
  }
  const enemies = rows.map(buildEnemy);
  const file = `/* eslint-disable max-lines */
// Auto-generated by scripts/parse-creatures.ts — do not edit manually.
import type { EnemyDef } from '../../../shared/types';

export const generatedCreatures: EnemyDef[] = [
${enemies.map(serializeEnemy).join('\n')}
];
`;
  writeFileSync(OUT_PATH, file, 'utf8');
  console.log(`Wrote ${enemies.length} creatures to ${OUT_PATH}`);
}

main();
